Metrics/LineLength:
  Max: 100
Style/TernaryParentheses:
  Enabled: false
Layout/FirstParameterIndentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
