attributes :id,
           :label,
           :mount_path,
           :enable_sftp,
           :borg_enabled,
           :borg_freq,
           :borg_strategy,
           :borg_keep_hourly,
           :borg_keep_daily,
           :borg_keep_weekly,
           :borg_keep_monthly,
           :borg_keep_annually,
           :borg_pre_backup,
           :borg_pre_restore,
           :borg_post_restore,
           :borg_rollback,
           :created_at,
           :updated_at